# Generated by Django 3.2 on 2023-05-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Тапсырыс', 'verbose_name_plural': 'Тапсырыстар'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Тапсырыс тауары', 'verbose_name_plural': 'Тапсырыс тауарлары'},
        ),
    ]
